export default interface ICatsData {
	name: string,
  id?: any | null,
	affection_level: number,
	adaptability: number,
	child_friendly: number,
	dog_friendly: number,
	grooming: number,
	health_issues: number,
	intelligence: number,
	hairless: number,
	energy_level: number,
	indoor: number,
	cfa_url: string,
	description: string,
	experimental:	number,
	hypoallergenic: number,
	image: object,
	lap: number,
	wikipedia_url: string
}